{% set name = "nbmake" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbmake-{{ version }}.tar.gz
  sha256: 49d5c59aefe45eaf8e2d8feff86c8e6de5547d823667305562364385e60d7206

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - ipykernel >=5.4.0
    - nbclient >=0.5.13,<1.0
    - nbformat >=5.0.8,<6.0.0
    - pydantic >=1.7.2,<2.0.0
    - pygments >=2.7.3,<3.0.0
    - pytest >=6.1.0

test:
  imports:
    - nbmake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/treebeardtech/nbmake
  summary: Pytest plugin for testing notebooks
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - epassaro
