{% set name = "nbmake" %}
{% set version = "1.5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nbmake-{{ version }}.tar.gz
  sha256: 239dc868ea13a7c049746e2aba2c229bd0f6cdbc6bfa1d22f4c88638aa4c5f5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - ipykernel >=5.4.0
    - nbclient >=0.6.6,<0.7.0
    - nbformat >=5.0.8,<6.0.0
    - pygments >=2.7.3,<3.0.0
    - pytest >=6.1.0

test:
  imports:
    - nbmake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/treebeardtech/nbmake
  summary: Pytest plugin for testing notebooks
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - epassaro
